### ISSUE TITLE
Add guidelines for contributing

### ISSUE THREAD

**Issue by petr-tik** [cratuki/solent#2]
If you want to grow a community around this, you should choose what workflow contributors should follow, as it will make your life easier in the future. 

Also, consider turning todo in markdown/orgfile into issues on GitHub, so people see where they can help

**Comment by cratuki** [comment]
Agree. Good issue. I've folded this into the priority epic, https://github.com/cratuki/solent/issues/4

**Comment by petr-tik** [comment]
Do you not think smaller issues are easier to digest?

**Comment by cratuki** [comment]
@petr-tik, please give more detail. What do you recommend? (I'm working myself out here, and this feedback will be interesting to me, so be assertive.)

Good next step for this task: look at Pieter Hintjen's C4 document to get guidelines on what to do here.
