### ISSUE TITLE
Create CI suite

### ISSUE THREAD

**Issue by cratuki** [cratuki/solent#7]
Not sure what this involves. Elsewhere petr-tik suggested this project goal, "ensure quality - ideally have a CI suite that runs tests on each commit, so at every point the master is a working artefact"

**Comment by cratuki** [comment]
Thought: may be able to get one of my digital ocean hosts set up to do regular pulls, and run a CI mechanism against from there.

Separately, I've seen mention of TravisCI functionality used in other projects. Should investigate what this is about.

**Comment by petr-tik** [comment]
TravisCI is well-known, also CircleCI is an option
